version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "18:00"
    timezone: Australia/Sydney
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: cjs-module-lexer
    versions:
    - 1.1.0
    - 1.1.1
    - 1.2.0
  - dependency-name: webpack
    versions:
    - 5.27.2
    - 5.28.0
    - 5.30.0
    - 5.31.0
    - 5.31.1
    - 5.31.2
    - 5.32.0
    - 5.33.2
    - 5.34.0
    - 5.35.0
    - 5.35.1
    - 5.36.0
  - dependency-name: solid-js
    versions:
    - 0.24.15
    - 0.24.16
    - 0.25.0
    - 0.25.1
    - 0.26.0
    - 0.26.1
    - 0.26.2
    - 0.26.3
    - 0.26.4
  - dependency-name: "@types/node"
    versions:
    - 14.14.35
    - 14.14.36
    - 14.14.37
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: esbuild
    versions:
    - 0.10.0
    - 0.10.1
    - 0.10.2
    - 0.11.0
    - 0.11.1
    - 0.11.10
    - 0.11.11
    - 0.11.12
    - 0.11.13
    - 0.11.14
    - 0.11.15
    - 0.11.2
    - 0.11.3
    - 0.11.4
    - 0.11.5
    - 0.11.6
    - 0.11.7
    - 0.11.8
    - 0.11.9
    - 0.9.6
    - 0.9.7
  - dependency-name: svelte-hmr
    versions:
    - 0.14.0
    - 0.14.1
    - 0.14.2
  - dependency-name: "@web/test-runner"
    versions:
    - 0.12.17
    - 0.12.18
    - 0.12.19
    - 0.13.0
    - 0.13.1
    - 0.13.2
  - dependency-name: pacote
    versions:
    - 11.3.2
  - dependency-name: "@npmcli/arborist"
    versions:
    - 2.4.0
  - dependency-name: postcss
    versions:
    - 8.2.10
    - 8.2.11
    - 8.2.12
    - 8.2.9
  - dependency-name: mini-css-extract-plugin
    versions:
    - 1.3.9
    - 1.4.0
    - 1.4.1
    - 1.5.0
  - dependency-name: core-js
    versions:
    - 3.10.0
    - 3.10.1
    - 3.10.2
    - 3.11.0
    - 3.9.1
  - dependency-name: open
    versions:
    - 8.0.4
    - 8.0.5
    - 8.0.6
  - dependency-name: "@babel/core"
    versions:
    - 7.13.10
    - 7.13.13
    - 7.13.14
    - 7.13.15
    - 7.13.16
  - dependency-name: ansi-styles
    versions:
    - 5.1.0
    - 5.2.0
    - 6.1.0
  - dependency-name: sass
    versions:
    - 1.32.11
    - 1.32.8
  - dependency-name: css-loader
    versions:
    - 5.1.4
    - 5.2.0
    - 5.2.1
    - 5.2.4
  - dependency-name: cssnano
    versions:
    - 4.1.11
    - 5.0.0
    - 5.0.1
  - dependency-name: rollup
    versions:
    - 2.42.3
    - 2.42.4
    - 2.43.0
    - 2.43.1
    - 2.44.0
    - 2.45.0
    - 2.45.1
    - 2.45.2
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.13.12
    - 7.13.15
  - dependency-name: "@auth0/auth0-spa-js"
    versions:
    - 1.14.0
  - dependency-name: ws
    versions:
    - 7.4.4
  - dependency-name: vue
    versions:
    - 3.0.10
    - 3.0.11
    - 3.0.7
    - 3.0.8
    - 3.0.9
  - dependency-name: "@babel/preset-typescript"
    versions:
    - 7.13.0
  - dependency-name: "@babel/preset-react"
    versions:
    - 7.12.13
    - 7.13.13
  - dependency-name: "@vue/compiler-sfc"
    versions:
    - 3.0.10
    - 3.0.11
    - 3.0.7
    - 3.0.8
    - 3.0.9
  - dependency-name: react
    versions:
    - 17.0.2
  - dependency-name: "@babel/plugin-proposal-class-properties"
    versions:
    - 7.13.0
  - dependency-name: "@babel/plugin-proposal-decorators"
    versions:
    - 7.13.5
  - dependency-name: "@types/chai"
    versions:
    - 4.2.15
    - 4.2.16
  - dependency-name: workerpool
    versions:
    - 6.1.3
  - dependency-name: mime-types
    versions:
    - 2.1.29
    - 2.1.30
  - dependency-name: "@types/ws"
    versions:
    - 7.4.1
  - dependency-name: svelte-preprocess
    versions:
    - 4.6.9
    - 4.7.0
  - dependency-name: p-queue
    versions:
    - 7.0.0
  - dependency-name: svelte
    versions:
    - 3.35.0
    - 3.36.0
  - dependency-name: "@babel/cli"
    versions:
    - 7.13.10
    - 7.13.14
  - dependency-name: jsdom
    versions:
    - 16.5.1
    - 16.5.2
  - dependency-name: webpack-cli
    versions:
    - 4.5.0
    - 4.6.0
  - dependency-name: "@types/react"
    versions:
    - 17.0.3
  - dependency-name: "@rollup/plugin-replace"
    versions:
    - 2.4.1
  - dependency-name: "@rollup/plugin-commonjs"
    versions:
    - 17.1.0
  - dependency-name: "@testing-library/react"
    versions:
    - 11.2.5
  - dependency-name: object.fromentries
    versions:
    - 2.0.4
  - dependency-name: fsevents
    versions:
    - 2.3.2
  - dependency-name: "@rollup/plugin-node-resolve"
    versions:
    - 11.2.0
  - dependency-name: react-dom
    versions:
    - 17.0.2
  - dependency-name: cacache
    versions:
    - 15.0.6
  - dependency-name: webpack-manifest-plugin
    versions:
    - 3.1.0
  - dependency-name: "@babel/plugin-syntax-class-properties"
    versions:
    - 7.12.13
  - dependency-name: chokidar
    versions:
    - 3.5.1
  - dependency-name: tippy.js
    versions:
    - 6.3.1
  - dependency-name: pug-code-gen
    versions:
    - 2.0.3
